device/urls.py
"""定义device的URL模式"""

from django.urls import path, re_path

from . import views

app_name = 'device '

urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    path('new_device', views.new_device, name='new_device'),
    re_path('edit_device/(?P<device_id>\d+)/', views.edit_device, name='edit_device'),
    re_path('return_device/(?P<device_id>\d+)/', views.return_device, name='return_device'),
]

device_manage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('device.urls', namespace='device')),
]

device/models.py
from django.db import models

import django.utils.timezone as timezone

# Create your models here.


class Device(models.Model):
    """设备名称"""
    device_name = models.CharField('设备名称', max_length=50)
    conference_room = models.CharField('使用地点', max_length=20)
    borrower = models.CharField('借  用  人', max_length=20)
    phone_number = models.CharField('联系电话', max_length=15)
    department = models.CharField('部    门', max_length=20)
    borrow_time = models.DateTimeField('借用日期', auto_now_add=True)
    expected_time = models.CharField('预计归还日期', max_length=20)
    actual_time = models.CharField('实际归还时间', default='未归还', max_length=20, null=True, blank=True)
    # remark = models.CharField(max_length=100)
    DONOT = '未归还'
    RERUENED = '已归还'
    REMARK_CHOICES = [
        (DONOT, '未归还'),
        (RERUENED, '已归还'),
    ]
    remark = models.CharField(
        '备注',
        max_length=20,
        choices=REMARK_CHOICES,
        default=DONOT,
    )

    def as_dict(self):
        return {
            "device_name": self.device_name,
            "conference_name": self.conference_room,
            "borrower": self.borrower,
            "phone_number": self.phone_number,
            "department": self.department,
            "borrow_time": self.borrow_time,
            "expected_time": self.expected_time,
            "actual_time": self.actual_time,
            "remark": self.remark,
            "id": self.id,
        }

    def __str__(self):
        """返回内容"""
        return self.device_name

device/forms.py
from django import forms
from .models import Device


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ['device_name', 'conference_room', 'borrower', 'phone_number', 'department', 'expected_time']
        labels = {
            'device_name': '设备名称',
            'conference_room': '使用地点',
        }


class ModifyForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ['device_name', 'remark']
        # labels = {}

device/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

from .models import Device
from .forms import DeviceForm, ModifyForm

import django.utils.timezone as timezone


def index(request):
    """设备管理的主页"""
    objects = Device.objects.order_by('borrow_time')
    items = [obj.as_dict() for obj in objects]
    return render(request, 'device/index.html', {'items': items})


def new_device(request):
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = DeviceForm()
    else:
        # POST提交的数据，对数据进行处理
        form = DeviceForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('device:index'))
    context = {'form': form}
    return render(request, 'device/new_device.html', context)


def edit_device(request, device_id):
    """编辑既有条目"""
    device = Device.objects.get(id=device_id)
    # device.actual_time = timezone.now().strftime("%Y-%m-%d")
    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = ModifyForm(instance=device)
    else:
        # POST提交的数据，对数据进行处理
        form = ModifyForm(instance=device, data=request.POST)
        if form.is_valid():
            if device.remark == '未归还':
                device.actual_time = '未归还'
                print('did')
            if device.remark == '已归还':
                # device.actual_time = timezone.now().strftime("%m{m}%d{d} %H:%m").format(m='月', d='日')
                device.actual_time = timezone.now().strftime("%m-%d %H:%m")
            form.save()
            return HttpResponseRedirect(reverse('device:index'))
    context = {'device': device, 'form': form}
    return render(request, 'device/edit_device.html', context)


def return_device(request, device_id):
    device = Device.objects.get(id=device_id)
    print(device.remark+'1')
    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = ModifyForm(instance=device)
    else:
        for key in request.POST.keys():
            print(key)
        for value in request.POST.values():
            print(value)
        # return HttpResponseRedirect(reverse('device:index'))
        form = ModifyForm(instance=device, data=request.POST)
        if form.is_valid():
            print('#######')
            if request.POST['submit'] == '取消':
                device.actual_time = '未归还'
                device.remark = '未归还'
                print('did')
            if request.POST['submit'] == '确定':
                # device.actual_time = timezone.now().strftime("%m{m}%d{d} %H:%m").format(m='月', d='日')
                device.actual_time = timezone.now().strftime("%m-%d %H:%m")
                device.remark = '已归还'
            form.save()
            return HttpResponseRedirect(reverse('device:index'))
    context = {'device': device, 'form': form}
    return render(request, 'device/return_device.html', context)

device/templates/device/edit_device.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit device</title>
    <link type="text/css" rel="styleSheet"  href="../static/style/index.css" />
</head>
<body>
{% block content %}
<p>Edit device</p>
<form action="{% url 'device:edit_device' device.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

</body>
</html>

device/templates/device/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" rel="styleSheet"  href="../static/style/index.css" />
</head>
<body>
<p>Device Manage</p>

{% block content %}
<a href="{% url 'device:new_device' %}">借用设备</a>
<p></p>

<table border="1">
    <thead>
    <tr>
        <th>设备名称</th>
        <th>使用地点</th>
        <th>借用日期</th>
        <th>借用人</th>
        <th>联系电话</th>
        <th>部门</th>
        <th>预计归还日期</th>
        <th>实际归还时间</th>
        <th>备注</th>
        <th>归还设备</th>
        <th>归还</th>
    </tr>
    </thead>
    <tbody>
    {% for device in items %}
    <tr>
        <td>{{ device.device_name }}</td>
        <td>{{ device.conference_name }}</td>
        <td>{{ device.borrow_time }}</td>
        <td>{{ device.borrower }}</td>
        <td>{{ device.phone_number}}</td>
        <td>{{ device.department }}</td>
        <td>{{ device.expected_time }}</td>
        <td>{{ device.actual_time }}</td>
        <td>{{ device.remark }}</td>
        <td><a href="{% url 'device:edit_device' device.id %}">归还设备</a></td>
        <td><a href="{% url 'device:return_device' device.id %}">归还</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

</body>
</html>

device/templates/device/new_device.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add device</title>
    <link type="text/css" rel="styleSheet"  href="../static/style/index.css" />
</head>
<body>
{% block content %}
<p>Add a new device:</p>

<form action="{% url 'device:new_device' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add device</button>
</form>
{% endblock content %}
</body>
</html>

device/templates/device/return_device.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .form{
            display: none;
        }
        .but{
            color: red;
        }
    </style>
</head>
<body>
{% block content %}

<p>return device</p>
<form
        action="{% url 'device:return_device' device.id %}"
        method="post"
>
    {% csrf_token %}
    <div class="form">
        {{ form.as_p }}
    </div>
    <button name="submit" value="确定" onclick="test()">确定</button>
</form>
<form
        action="{% url 'device:return_device' device.id %}"
        method="post"
>
    {% csrf_token %}
    <div class="form">
        {{ form.as_p }}
    </div>
    <button name="submit" value="取消" onclick="test()" class="but">取消</button>
</form>
{% endblock content %}

</body>
</html>